name = "Dracula"

bg = "#282a36"
fg = "#f8f8f2"
gutter_bg = "#21222c"
gutter_border = "#44475a"
line_fg = "#6272a4"
line_hl = "#f8f8f0"
sel = "#44475a"
current_line = "#343746"
match_bracket = "#8be9fd"
comment = "#6272a4"
string = "#f1fa8c"
number = "#bd93f9"
keyword = "#8be9fd"
command = "#8be9fd"
control = "#ff79c6"
variable = "#ffb86c"
operator = "#ff79c6"
function = "#50fa7b"
bracket = "#f8f8f2"
builtin = "#bd93f9"
toolbar_bg = "#21222c"
toolbar_fg = "#f8f8f2"
tab_bg = "#282a36"
tab_active = "#44475a"
output_bg = "#21222c"
output_fg = "#6272a4"
output_err = "#ff5555"
output_ok = "#50fa7b"
dock_bg = "#282a36"
dock_fg = "#f8f8f2"
menu_bg = "#282a36"
menu_fg = "#f8f8f2"
statusbar_bg = "#21222c"
statusbar_fg = "#6272a4"
scrollbar = "#44475a"
scrollbar_hover = "#6272a4"
autocomplete_bg = "#44475a"
autocomplete_fg = "#f8f8f2"
autocomplete_sel = "#6272a4"
accent = "#bd93f9"
