name = "Monokai"

bg = "#272822"
fg = "#f8f8f2"
gutter_bg = "#1e1f1c"
gutter_border = "#3e3d32"
line_fg = "#75715e"
line_hl = "#f8f8f0"
sel = "#49483e"
current_line = "#33342e"
match_bracket = "#66d9ef"
comment = "#75715e"
string = "#e6db74"
number = "#ae81ff"
keyword = "#66d9ef"
command = "#66d9ef"
control = "#f92672"
variable = "#fd971f"
operator = "#f92672"
function = "#a6e22e"
bracket = "#f8f8f2"
builtin = "#ae81ff"
toolbar_bg = "#1e1f1c"
toolbar_fg = "#f8f8f2"
tab_bg = "#272822"
tab_active = "#3e3d32"
output_bg = "#1e1f1c"
output_fg = "#a59f85"
output_err = "#f92672"
output_ok = "#a6e22e"
dock_bg = "#272822"
dock_fg = "#f8f8f2"
menu_bg = "#272822"
menu_fg = "#f8f8f2"
statusbar_bg = "#1e1f1c"
statusbar_fg = "#a59f85"
scrollbar = "#49483e"
scrollbar_hover = "#75715e"
autocomplete_bg = "#3e3d32"
autocomplete_fg = "#f8f8f2"
autocomplete_sel = "#49483e"
accent = "#66d9ef"
