name = "Nord"

bg = "#2e3440"
fg = "#d8dee9"
gutter_bg = "#272c36"
gutter_border = "#3b4252"
line_fg = "#4c566a"
line_hl = "#eceff4"
sel = "#434c5e"
current_line = "#353b49"
match_bracket = "#88c0d0"
comment = "#4c566a"
string = "#a3be8c"
number = "#b48ead"
keyword = "#81a1c1"
command = "#81a1c1"
control = "#bf616a"
variable = "#ebcb8b"
operator = "#81a1c1"
function = "#88c0d0"
bracket = "#eceff4"
builtin = "#d08770"
toolbar_bg = "#272c36"
toolbar_fg = "#d8dee9"
tab_bg = "#2e3440"
tab_active = "#3b4252"
output_bg = "#272c36"
output_fg = "#4c566a"
output_err = "#bf616a"
output_ok = "#a3be8c"
dock_bg = "#2e3440"
dock_fg = "#d8dee9"
menu_bg = "#2e3440"
menu_fg = "#d8dee9"
statusbar_bg = "#272c36"
statusbar_fg = "#4c566a"
scrollbar = "#434c5e"
scrollbar_hover = "#4c566a"
autocomplete_bg = "#3b4252"
autocomplete_fg = "#d8dee9"
autocomplete_sel = "#434c5e"
accent = "#88c0d0"
